Find non-matching parallax and diffuse textures
hakasapl/ParallaxGen pull request #26
Opened 2024-10-15 14:21 UTC by Sebastian-81

Missing TODOs: command line parameter to specify the past and testing with MO2

Filtering of the warnings is not implemented yet I see it as a nice-to-have feature and should probably be implemented in a way that can handle wildcards and both mod names as well as BSAs

2024-10-15 14:23 UTC, Sebastian-81 commented on ParallaxGen/src/main.cpp
> +  // TODO get path as command line argument
TODO

2024-10-15 17:02 UTC, hakasapl requested changes
Left some comments, also unit tests would be good for the new methods.

I have written some code for the CLI argument piece, when I get access to your branch I can push them

2024-10-15 17:02 UTC, hakasapl commented on ParallaxGen/src/main.cpp
> +  // TODO test with MO2
Seems to work with MO2, not tested extensively yet

2024-10-15 17:02 UTC, hakasapl commented on ParallaxGen/src/main.cpp
> +        "cause visual problems if the textures don't match. Run with --vv to get a list of all textures in the logs.");
`-v` should be all that is needed to see the individual textures in my opinion. `-vv` should almost always exclusively be for devs trying to debug stuff

2024-10-15 17:02 UTC, hakasapl commented on ParallaxGen/src/main.cpp
> +      spdlog::warn(L"{} ---> {}", Pair.first, Pair.second);
Add a prefix to this (each log message should be understood on its own, without the need to see the first warning). I cam up with `Potential Mod Mismatch` but there's probably something better
```suggestion
      spdlog::warn(L"Potential Mod Mismatch: {} ---> {}", Pair.first, Pair.second);
```

2024-10-15 17:02 UTC, hakasapl commented on ParallaxGenLib/src/ModManagerDirectory.cpp
> +  }
BSA support here would be good. Take a look at `BethesdaDirectory::addBSAToFileMap` for something similar. You can also see `BethesdaDirectory::getFile` to see how you can read the bytes from a BSA file for CRC32 later.

2024-10-15 17:02 UTC, hakasapl commented on ParallaxGenLib/src/ParallaxGenDirectory.cpp
> +      ParallaxMod = MD.GetModFromTexture(ParallaxModPath);
This is static
```suggestion
      ParallaxMod = ModManagerDirectory::GetModFromTexture(ParallaxModPath);
```

2024-10-15 17:02 UTC, hakasapl commented on ParallaxGenLib/src/ParallaxGenDirectory.cpp
> +      DiffuseMod = MD.GetModFromTexture(DiffuseModPath);
This is static
```suggestion
      ParallaxMod = ModManagerDirectory::GetModFromTexture(ParallaxModPath);
```

2024-10-15 18:34 UTC, Sebastian-81 commented on ParallaxGenLib/src/ModManagerDirectory.cpp
> +  }
Do you have something in mind where we need it now ot can we do it later?

2024-10-16 14:12 UTC, hakasapl commented on ParallaxGenLib/src/ModManagerDirectory.cpp
> +  }
I see, yeah no we don't need to read BSAs again here, but I think we should read what the winning bsa is from BethesdaDirectory and find it somewhere here as well (maybe also find BSA files?). Basically I want to be able to give a warning if a mod's diffuse is in a BSA and parallax in a different mod as loose file or BSA

2024-10-16 14:22 UTC, Sebastian-81 commented on ParallaxGenLib/src/ModManagerDirectory.cpp
> +  }
That's implemented already here: https://github.com/hakasapl/ParallaxGen/blob/e5b8eb14ebdab8c5981bf1dfc85fd127d7e53d77/ParallaxGenLib/src/ParallaxGenDirectory.cpp#L469

2024-10-16 14:35 UTC, Sebastian-81 commented on ParallaxGen/src/main.cpp
There should be a warning to the user if he does not provide that directory ParallaxGen can not find mismatching textures and he may have visual errors

2024-10-27 22:21 UTC, hakasapl commented
Closing in favor of https://github.com/hakasapl/ParallaxGen/pull/32

2024-10-27 22:21 UTC, closed without merging